os:
  - linux

language: cpp
dist: focal

before_install:
  - pip install --user cpp-coveralls

addons:
  apt:
    packages:
      - catch
      - cmake
      - qtbase5-dev
      - libfreeimageplus-dev
      - doxygen
      - cppcheck
      # Currently crashing on travis for some reason
      # - libclang-10-dev
      # - clang-tools-10
      # - clang-format-10
      # - clang-tidy-10
      - liblog4cxx-dev
      - libboost-all-dev
      - lcov

branches:
  only:
    - master
    - devel

script:
  - mkdir -p build && cd build
  - >
    cmake
    -DCMAKE_BUILD_TYPE=DEV
    -DRCPPSW_AL_MT_SAFE_TYPES=YES
    -DLIBRA_TESTS=yes
    -DLIBRA_CODE_COV=yes
    ..
  - make build-and-test
  - >
    cmake
    -DCMAKE_BUILD_TYPE=DEV
    -DRCPPSW_AL_MT_SAFE_TYPES=NO
    -DLIBRA_TESTS=yes
    -DLIBRA_CODE_COV=yes
    ..
    - make build-and-test
  - >
    cmake
    -DCMAKE_BUILD_TYPE=OPT
    -DRCPPSW_AL_MT_SAFE_TYPES=YES
    -DLIBRA_TESTS=yes
    -DLIBRA_CODE_COV=yes
    ..
    - make build-and-test
  - >
    cmake
    -DCMAKE_BUILD_TYPE=OPT
    -DRCPPSW_AL_MT_SAFE_TYPES=NO
    -DLIBRA_TESTS=yes
    -DLIBRA_CODE_COV=yes
    ..
    - make build-and-test

after_success:
  - coveralls --root .. -E '.*/ext/.*' -E '.*/CMakeFiles/.*'
