rcppsw::math::vector2
using rcppsw::math::vector2< T >::value_type = T
constexpr size_t rcppsw::math::vector2< T >::kDIMENSIONALITY
const vector2d rcppsw::math::vector2d::X
The positive X axis.
const vector2d rcppsw::math::vector2d::Y
The positive Y axis.
T rcppsw::math::vector2< T >::m_x
T rcppsw::math::vector2< T >::m_y
static size_t rcppsw::math::vector2< T >::l1norm(const vector2< U > &v1, const vector2< V > &v2)
Computes the manhattan distance between the passed vectors.
rcppsw::math::vector2< T >::vector2(const T &length, const radians &angle) noexcept
Initializes the vector coordinates from polar coordinates.
length The vector length. angle The vector angle.
constexpr rcppsw::math::vector2< T >::vector2(const T &x, const T &y) noexcept
Initializes the vector from Cartesian coordinates.
x The X coordinate. y The Y coordinate.
rcppsw::math::vector2< T >::vector2(void) noexcept=default
Initializes vector to (0,0)
radians rcppsw::math::vector2< T >::angle(void) const
Return the angle of this vector.
bool rcppsw::math::vector2< T >::is_pd(void) const
Is the vector is positive definite?
bool rcppsw::math::vector2< T >::is_psd(void) const
Is the vector is positive semi-definite?
double rcppsw::math::vector2< T >::length(void) const
Returns the length of this vector.
vector2& rcppsw::math::vector2< T >::normalize(void)
Normalizes this vector.
After this method is called, the vector has length 1. If the vector is (0,0), this call results in a division by zero error, and your program will probably crash. A reference to the normalized vector.
bool rcppsw::math::vector2< T >::operator!=(const vector2 &other) const
Returns if this vector and the passed one are not equal by checking coordinates for equality.
Should generally not be called if the template parameter type is not an integer, as floating point comparisons in general are unsafe.
vector2 rcppsw::math::vector2< T >::operator*(T val) const
vector2& rcppsw::math::vector2< T >::operator*=(T val)
vector2 rcppsw::math::vector2< T >::operator+(const vector2 &other) const
vector2& rcppsw::math::vector2< T >::operator+=(const vector2 &other)
vector2<T> rcppsw::math::vector2< T >::operator-(const vector2 &other) const
vector2 rcppsw::math::vector2< T >::operator-(void) const
vector2& rcppsw::math::vector2< T >::operator-=(const vector2 &other)
vector2 rcppsw::math::vector2< T >::operator/(T val) const
vector2& rcppsw::math::vector2< T >::operator/=(T val)
bool rcppsw::math::vector2< T >::operator<(const vector2 &other) const
Needed for using vectors as keys in a map.
bool rcppsw::math::vector2< T >::operator<=(const vector2 &other) const
bool rcppsw::math::vector2< T >::operator==(const vector2 &other) const
Returns if this vector and the argument are considered equal, determined by coordinate comparison.
Only available if the template argument is not floating point.
bool rcppsw::math::vector2< T >::operator==(const vector2 &other) const
Returns if this vector and the argument are considered equal, determined by coordinate comparison.
Only available if the template argument is floating point.
bool rcppsw::math::vector2< T >::operator>(const vector2 &other) const
bool rcppsw::math::vector2< T >::operator>=(const vector2 &other) const
vector2& rcppsw::math::vector2< T >::rotate(const radians &angle)
Rotate this vector by the specified angle.
This is only available if the template parameter is not an integer. angle The rotation angle. A reference to the rotated vector.
vector2& rcppsw::math::vector2< T >::scale(const T &factor)
Scales the vector by the specified values.
factor The scaling factor applied to both X and Y. A reference to the scaled vector.
vector2& rcppsw::math::vector2< T >::scale(const T &scale_x, const T &scale_y)
Scales the vector by the specified values.
scale_x the scale factor for the X coordinate. scale_y the scale factor for the Y coordinate. A reference to the scaled vector.
void rcppsw::math::vector2< T >::set(const T &x, const T &y)
Sets the vector contents from Cartesian coordinates.
x The new X coordinate. y The new Y coordinate.
References rcppsw::math::radians::v.
void rcppsw::math::vector2< T >::set_from_polar(const T &length, const radians &angle)
Sets the vector contents from polar coordinates. length The length of the vector. angle The angle of the vector (range [0,2pi)
T rcppsw::math::vector2< T >::square_length(void) const
Returns the square length of this vector.
std::string rcppsw::math::vector2< T >::to_str(void) const override
Return a string representation of a class.
void rcppsw::math::vector2< T >::x(const T &x)
T rcppsw::math::vector2< T >::x(void)
References rcppsw::math::vector2< T >::x.
Referenced by rcppsw::ds::stacked_grid2D< TupleTypes >::access, rcppsw::ds::base_grid2D< ral::mt_size_t >::contains, rcppsw::math::vector2< T >::x.
const T& rcppsw::math::vector2< T >::x(void) const
void rcppsw::math::vector2< T >::y(const T &y)
T rcppsw::math::vector2< T >::y(void)
References rcppsw::math::vector2< T >::y.
Referenced by rcppsw::ds::stacked_grid2D< TupleTypes >::access, rcppsw::ds::base_grid2D< ral::mt_size_t >::contains, rcppsw::math::vector2< T >::y.
const T& rcppsw::math::vector2< T >::y(void) const
std::ostream& operator<<(std::ostream &stream, const vector2 &v)
std::istream& operator>>(std::istream &is, vector2< T > &v)
For parsing a vector from a string in the form of "X,Y".