rcppsw::math::bounding_box
using rcppsw::math::bounding_box< TCoord >::coord_type = TCoord
using rcppsw::math::bounding_box< TCoord >::coord_value_type = typename coord_type::value_type
coord_type rcppsw::math::bounding_box< TCoord >::m_anchor
bool rcppsw::math::bounding_box< TCoord >::m_anchor_initialized
coord_type rcppsw::math::bounding_box< TCoord >::m_center
rmath::range<coord_value_type> rcppsw::math::bounding_box< TCoord >::m_xspan
rmath::range<coord_value_type> rcppsw::math::bounding_box< TCoord >::m_yspan
rmath::range<coord_value_type> rcppsw::math::bounding_box< TCoord >::m_zspan
const coord_type rcppsw::math::bounding_box< TCoord >::mc_dims
rcppsw::math::bounding_box< TCoord >::bounding_box(bounding_box &&)=default
rcppsw::math::bounding_box< TCoord >::bounding_box(const bounding_box &)=default
rcppsw::math::bounding_box< TCoord >::bounding_box(const coord_type &dims)
rcppsw::math::bounding_box< TCoord >::bounding_box(const coord_type &dims, const coord_type &anchor)
rcppsw::math::bounding_box< TCoord >::~bounding_box(void) override=default
const coord_type& rcppsw::math::bounding_box< TCoord >::anchor3D(void) const
coord_type rcppsw::math::bounding_box< TCoord >::center3D(void) const
Referenced by rcppsw::ds::graph::hgrid3D_view< TSpecType >::Func.
const coord_type& rcppsw::math::bounding_box< TCoord >::dims3D(void) const
Referenced by rcppsw::ds::graph::hgrid3D_view< TSpecType >::Func.
bounding_box& rcppsw::math::bounding_box< TCoord >::operator=(bounding_box &&)=default
bounding_box& rcppsw::math::bounding_box< TCoord >::operator=(const bounding_box &)=default
void rcppsw::math::bounding_box< TCoord >::update(const coord_type &anchor)
coord_value_type rcppsw::math::bounding_box< TCoord >::xsize(void) const
Referenced by rcppsw::ds::graph::hgrid3D_view< TSpecType >::n_vertices.
rmath::range<coord_value_type> rcppsw::math::bounding_box< TCoord >::xspan(void) const
coord_value_type rcppsw::math::bounding_box< TCoord >::ysize(void) const
rmath::range<coord_value_type> rcppsw::math::bounding_box< TCoord >::yspan(void) const
Referenced by rcppsw::ds::graph::hgrid3D_view< TSpecType >::Func.
coord_value_type rcppsw::math::bounding_box< TCoord >::zsize(void) const
rmath::range<coord_value_type> rcppsw::math::bounding_box< TCoord >::zspan(void) const
Referenced by rcppsw::ds::graph::hgrid3D_view< TSpecType >::Func.