rcppsw::math::vector3
using rcppsw::math::vector3< T >::value_type = T
constexpr size_t rcppsw::math::vector3< T >::kDIMENSIONALITY
const vector3d rcppsw::math::vector3d::X
The positive X axis.
const vector3d rcppsw::math::vector3d::Y
The positive Y axis.
const vector3d rcppsw::math::vector3d::Z
The positive Z axis.
T rcppsw::math::vector3< T >::m_x
T rcppsw::math::vector3< T >::m_y
T rcppsw::math::vector3< T >::m_z
constexpr rcppsw::math::vector3< T >::vector3(const T &x, const T &y, const T &z)
Initializes the vector from Cartesian coordinates.
x The X coordinate. y The Y coordinate. z The Z coordinate.
rcppsw::math::vector3< T >::vector3(const vector2< T > &v)
Initializes the 3D vector from a 2D vector, setting the Z value to 0.0.
rcppsw::math::vector3< T >::vector3(const vector2< T > &v, const T &z)
Initialize the 3D vector from a 2D vector.
rcppsw::math::vector3< T >::vector3(void) noexcept=default
Initializes vector to (0,0,0)
bool rcppsw::math::vector3< T >::is_pd(void) const
Is the vector is positive definite?
bool rcppsw::math::vector3< T >::is_psd(void) const
Is the vector is positive semi-definite?
double rcppsw::math::vector3< T >::length(void) const
Returns the length of this vector.
vector3 rcppsw::math::vector3< T >::mask(const vector3 &the_mask) const
Mask a vector using another vector, using mask as a boolean mask by treating each non-zero entry as a 1. Should only be used if mask is a unit vector.
vector3& rcppsw::math::vector3< T >::normalize(void)
Normalizes this vector.
After this method is called, the vector has length 1. If the vector is (0,0), this call results in a division by zero error, and your program will probably crash. A reference to the normalized vector.
bool rcppsw::math::vector3< T >::operator!=(const vector3 &other) const
Returns if this vector and the passed one are not equal by checking coordinates for equality.
Should generally not be called if the template parameter type is not an integer, as floating point comparisons in general are unsafe.
vector3 rcppsw::math::vector3< T >::operator*(const T &val) const
vector3& rcppsw::math::vector3< T >::operator*=(const T &val)
vector3 rcppsw::math::vector3< T >::operator+(const vector3 &other) const
vector3& rcppsw::math::vector3< T >::operator+=(const vector3 &other)
vector3<T> rcppsw::math::vector3< T >::operator-(const vector3 &other) const
vector3 rcppsw::math::vector3< T >::operator-(void) const
vector3& rcppsw::math::vector3< T >::operator-=(const vector3 &other)
vector3 rcppsw::math::vector3< T >::operator/(const T &val) const
vector3& rcppsw::math::vector3< T >::operator/=(const T &val)
bool rcppsw::math::vector3< T >::operator==(const vector3 &other) const
Returns if this vector and the argument are considered equal, determined by coordinate comparison.
Only available if the template argument is not floating point.
bool rcppsw::math::vector3< T >::operator==(const vector3 &other) const
Returns if this vector and the argument are considered equal, determined by coordinate comparison.
Only available if the template argument is floating point.
bool rcppsw::math::vector3< T >::operator>(const vector3 &other) const
References rcppsw::math::kDOUBLE_EPSILON.
bool rcppsw::math::vector3< T >::operator>(const vector3 &other) const
vector2<T> rcppsw::math::vector3< T >::project_on_xy(void) const
Calculates the projection of this vector onto the XY plane.
vector2<T> rcppsw::math::vector3< T >::project_on_xz(void) const
Calculates the projection of this vector onto the XZ plane.
vector2<T> rcppsw::math::vector3< T >::project_on_yz(void) const
Calculates the projection of this vector onto the YZ plane.
vector3& rcppsw::math::vector3< T >::scale(const T &factor)
Scales the vector by the specified values.
factor The scaling factor applied to X,Y,Z. A reference to the scaled vector.
vector3& rcppsw::math::vector3< T >::scale(const T &scale_x, const T &scale_y, const T &scale_z)
Scales the vector by the specified values.
scale_x The scale factor for the X coordinate. scale_y The scale factor for the Y coordinate. scale_z The scale factor for the Z coordinate. A reference to the scaled vector.
void rcppsw::math::vector3< T >::set(const T &x, const T &y, const T &z)
Sets the vector contents from Cartesian coordinates.
x The new X coordinate. y The new Y coordinate.
T rcppsw::math::vector3< T >::square_length(void) const
Returns the square length of this vector.
vector2<T> rcppsw::math::vector3< T >::to_2D(void) const
sphere_vector<T> rcppsw::math::vector3< T >::to_spherical(void) const
std::string rcppsw::math::vector3< T >::to_str(void) const override
Return a string representation of a class.
void rcppsw::math::vector3< T >::x(const T &x)
References rcppsw::math::vector3< T >::x.
Referenced by rcppsw::math::vector3< T >::x.
T rcppsw::math::vector3< T >::x(void)
Referenced by rcppsw::ds::base_grid3D< ral::mt_size_t >::contains.
const T& rcppsw::math::vector3< T >::x(void) const
References rcppsw::math::vector3< T >::x.
Referenced by rcppsw::math::vector3< T >::x.
radians rcppsw::math::vector3< T >::xangle(void) const
Return angle between this vector and the X axis.
void rcppsw::math::vector3< T >::y(const T &y)
T rcppsw::math::vector3< T >::y(void)
Referenced by rcppsw::ds::base_grid3D< ral::mt_size_t >::contains.
const T& rcppsw::math::vector3< T >::y(void) const
References rcppsw::math::vector3< T >::y.
Referenced by rcppsw::math::vector3< T >::y.
radians rcppsw::math::vector3< T >::yangle(void) const
Return the angle between this vector and the Y axis.
void rcppsw::math::vector3< T >::z(const T &z)
T rcppsw::math::vector3< T >::z(void)
Referenced by rcppsw::ds::base_grid3D< ral::mt_size_t >::contains.
const T& rcppsw::math::vector3< T >::z(void) const
References rcppsw::math::vector3< T >::z.
Referenced by rcppsw::math::vector3< T >::z.
radians rcppsw::math::vector3< T >::zangle(void) const
Return the angle between this vector and the Z axis.
std::ostream& operator<<(std::ostream &stream, const vector3 &v)
std::istream& operator>>(std::istream &is, vector3< T > &v)
For parsing a vector from a string in the form of "X,Y,Z".