graph.hpp
static auto add_edge(TBGLGraphType &g, typename TBGLGraphType::vertex_descriptor u, typename TBGLGraphType::vertex_descriptor v)
static auto add_vertex(TBGLGraphType &g)
static auto adjacent_vertices(const TBGLGraphType &g, typename TBGLGraphType::vertex_descriptor v)
static bool contains(const TBGLGraphType &g, const rmath::vector3z &c)
Determine if g contains a vertex with coordinates c.
References find.
Referenced by rcppsw::ds::base_grid2D< ral::mt_size_t >::contains, rcppsw::ds::base_grid3D< ral::mt_size_t >::contains, rcppsw::math::range< coord_value_type >::contains.
static boost::optional<typename TBGLGraphType::vertex_descriptor> find(const TBGLGraphType &g, const TCoordType &c)
Search for the vertex with coordinates c in g.
The descriptor of the matching vertex, or -1 if not found.
References vertices.
Referenced by contains.
static size_t n_vertices(const TBGLGraphType &g)
Get the # of vertices in g.
static auto out_degree(const TBGLGraphType &g, const typename TBGLGraphType::vertex_descriptor &v)
static auto out_edges(const TBGLGraphType &g, const typename TBGLGraphType::vertex_descriptor &v)
static auto remove_vertex(TBGLGraphType &g, typename TBGLGraphType::vertex_descriptor v)
static auto target(const TBGLGraphType &g, const typename TBGLGraphType::edge_descriptor &e)
static auto vertex_properties(const TBGLGraphType &g)
References vertices.
static auto vertices(const TBGLGraphType &g) -> decltype(boost::vertices(std::declval< const TBGLGraphType >()))
Get the vertices in the specified graph, as an iterator range.
We can't use boost::make_iterator_range here, because that doesn't work with filtered_graph types, for whatever reason.
Referenced by find, vertex_properties.