rcppsw
constexpr std::underlying_type<TEnum>::type rcppsw::as_underlying(const TEnum &e) noexcept
Get the value of a strongly typed enum as its underlying type.
std::string rcppsw::to_string(const T &obj)
For T where std::to_string(T) works let the stdandard library to the conversion.
For T where std::to_string(T) does not work, if T defines a to_str() method, then it can still use rcppsw::to_string().
Referenced by rcppsw::metrics::csv_sink::csv_entry_intavg, rcppsw::ds::metrics::grid2D_metrics_csv_sink< TCellOp >::csv_header_cols, rcppsw::ds::metrics::grid3D_metrics_csv_sink< TCellOp >::csv_header_cols.