rcppsw::math
using rcppsw::math::ranged = typedef range<double>
Specialization of range for doubles.
using rcppsw::math::rangei = typedef range<int>
Specialization of range for signed integers.
using rcppsw::math::rangez = typedef range<size_t>
Specialization of range for size_t.
using rcppsw::math::vector2d = typedef vector2<double>
Specialization of vector2 for doubles.
using rcppsw::math::vector2i = typedef vector2<int>
Specialization of vector2 for signed integers.
using rcppsw::math::vector2z = typedef vector2<size_t>
Specialization of vector2 for size_t.
using rcppsw::math::vector3d = typedef vector3<double>
Specialization of vector3 for doubles.
using rcppsw::math::vector3i = typedef vector3<int>
Specialization of vector3 for signed integers.
using rcppsw::math::vector3z = typedef vector3<size_t>
Specialization of vector3 for size_t.
constexpr double rcppsw::math::kDOUBLE_EPSILON
For comparing floating point numbers within a given tolerance when std::numeric_limits<double>::epsilon() won't work.
Referenced by rcppsw::algorithm::clustering::nc_cluster< T, Policy >::converged, rcppsw::math::degrees::operator>, rcppsw::math::vector3< T >::operator>.
TAngleType rcppsw::math::abs(const TAngleType &angle)
Calculate the absolute value of a radians or degrees value. This does not perform any wrapping/normalizing.
Referenced by dvec2ivec, rcppsw::math::vector2< T >::componentwise_compare::operator().
static rangez rcppsw::math::drange2zrange(const rangez &other, double scale)
static vector2i rcppsw::math::dvec2ivec(const vector2d &other, double scale)
References abs.
static vector3i rcppsw::math::dvec2ivec(const vector3d &other, double scale)
References abs.
static vector2z rcppsw::math::dvec2zvec(const vector2d &other, double scale)
static vector3z rcppsw::math::dvec2zvec(const vector3d &other, double scale)
static ranged rcppsw::math::irange2drange(const rangei &other)
static ranged rcppsw::math::irange2drange(const rangei &other, double scale)
static bool rcppsw::math::is_equal(double lhs, double rhs, double tol=kDOUBLE_EPSILON)
Determine if two floating point values are equal, using the specified tolerance. You can't always use std::numeric_limits<double>::epsilon() because of floating point representation errors.
static bool rcppsw::math::is_multiple_of(double x, double y, double tol=kDOUBLE_EPSILON)
Determine if x is a multiple y within tol tolerance.
static vector2d rcppsw::math::ivec2dvec(const vector2i &other)
static vector2d rcppsw::math::ivec2dvec(const vector2i &other, double scale)
static vector3d rcppsw::math::ivec2dvec(const vector3i &other)
static vector3d rcppsw::math::ivec2dvec(const vector3i &other, double scale)
static size_t rcppsw::math::l1norm(const vector2< U > &v1, const vector2< V > &v2)
Computes the distance between the passed vectors.
static size_t rcppsw::math::l1norm(const vector3< U > &v1, const vector3< V > &v2)
Computes the distance between the passed vectors.
static double rcppsw::math::l2norm(const T &lhs, const T &rhs)
Computes the euclidean distance between the passed vectors.
Referenced by rcppsw::ds::graph::detail::hgrid3D_view_builder< TSpecType >::hgrid3D_view_builder.
static double rcppsw::math::l2norm_squared(const T &lhs, const T &rhs)
Computes the square of the euclidean distance between the passed vectors.
static double rcppsw::math::normalize(double min, double max, double val)
degrees rcppsw::math::normalized_diff(const degrees &angle1, const degrees &angle2)
Calculates the normalized difference between the given angles.
The difference is calculated as (angle1 - angle2) and then normalized in [-180,180]. The difference between the two angles.
radians rcppsw::math::normalized_diff(const radians &angle1, const radians &angle2)
Calculates the normalized difference between the given angles.
The difference is calculated as (angle1 - angle2) and then normalized in [-pi,pi]. The difference between the two angles.
ema<T> rcppsw::math::operator*(const ema< T > &lhs, const U &rhs)
ema<T> rcppsw::math::operator*(const U &lhs, const ema< T > &rhs)
rmath::radians rcppsw::math::operator*(double lhs, const rmath::radians &rhs)
ema<T> rcppsw::math::operator-(const ema< T > &lhs, const U &rhs)
ema<T> rcppsw::math::operator-(const U &lhs, const ema< T > &rhs)
ema<T> rcppsw::math::operator/(const ema< T > &lhs, const double &rhs)
ema<T> rcppsw::math::operator/(const U &lhs, const ema< T > &rhs)
std::ostream& rcppsw::math::operator<<(std::ostream &stream, const degrees &d)
std::ostream& rcppsw::math::operator<<(std::ostream &stream, const radians &r)
bool rcppsw::math::operator==(const T &v, const ema< T > &rhs)
degrees rcppsw::math::to_degrees(const radians &r)
Converts radians to degrees,.
radians rcppsw::math::to_radians(const degrees &d)
Converts degrees to radians.
static rmath::ranged rcppsw::math::xspan(const TCoord &anchor, const double &dim)
Calculate the span in {X,Y,Z} in real coordinates of an entity given the position of its 3D center and dimension in {X,Y<Z}.
The span in {X,Y,Z} of the entity.
static rmath::rangez rcppsw::math::xspan(const TCoord &anchor, size_t dim)
Calculate the span in {X,Y,Z} in discrete coordinates of an entity given its discrete anchor (2D or 3D) and {X,Y,Z} dimension.
This function can only be called for entities which have a defined discrete center. The span in {X,Y,Z} of the entity (closed interval).
static rmath::ranged rcppsw::math::yspan(const TCoord &anchor, const double &dim)
static rmath::rangez rcppsw::math::yspan(const TCoord &anchor, size_t dim)
static ranged rcppsw::math::zrange2drange(const rangez &other)
static ranged rcppsw::math::zrange2drange(const rangez &other, double scale)
static rmath::ranged rcppsw::math::zspan(const TCoord &anchor, const double &dim)
static rmath::rangez rcppsw::math::zspan(const TCoord &anchor, size_t dim)
static vector2d rcppsw::math::zvec2dvec(const vector2z &other)
static vector2d rcppsw::math::zvec2dvec(const vector2z &other, double scale)
static vector3d rcppsw::math::zvec2dvec(const vector3z &other)
static vector3d rcppsw::math::zvec2dvec(const vector3z &other, double scale)