.TH "/home/jharwell/git/rcppsw/include/rcppsw/types Directory Reference" 3 "Sat Feb 5 2022" "RCPPSW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/jharwell/git/rcppsw/include/rcppsw/types Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBdiscretize_ratio\&.hpp\fP"
.br
.ti -1c
.RI "file \fBdistance_measure\&.hpp\fP"
.br
.ti -1c
.RI "file \fBmanhattan_dist\&.hpp\fP"
.br
.ti -1c
.RI "file \fBnamed_type\&.hpp\fP"
.br
.ti -1c
.RI "file \fBspatial_dist\&.hpp\fP"
.br
.ti -1c
.RI "file \fBspatial_range\&.hpp\fP"
.br
.ti -1c
.RI "file \fBtimestep\&.hpp\fP"
.br
.ti -1c
.RI "file \fBtype_uuid\&.hpp\fP"
.br
.in -1c
