.TH "/home/jharwell/git/rcppsw/include/rcppsw/patterns/decorator Directory Reference" 3 "Sat Feb 5 2022" "RCPPSW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/jharwell/git/rcppsw/include/rcppsw/patterns/decorator Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBdecorator\&.hpp\fP"
.br
.in -1c
