.TH "/home/jharwell/git/rcppsw/include/rcppsw/metrics/config Directory Reference" 3 "Sat Feb 5 2022" "RCPPSW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/jharwell/git/rcppsw/include/rcppsw/metrics/config Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBxml\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBfile_sink_config\&.hpp\fP"
.br
.ti -1c
.RI "file \fBmetrics_config\&.hpp\fP"
.br
.ti -1c
.RI "file \fBnetwork_sink_config\&.hpp\fP"
.br
.ti -1c
.RI "file \fBoutput_mode_config\&.hpp\fP"
.br
.in -1c
