.TH "/home/jharwell/git/rcppsw/include/rcppsw/math Directory Reference" 3 "Sat Feb 5 2022" "RCPPSW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/jharwell/git/rcppsw/include/rcppsw/math Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBconfig\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBangles\&.hpp\fP"
.br
.ti -1c
.RI "file \fBbinned_powerlaw_distribution\&.hpp\fP"
.br
.ti -1c
.RI "file \fBbounding_box\&.hpp\fP"
.br
.ti -1c
.RI "file \fBdegrees\&.hpp\fP"
.br
.ti -1c
.RI "file \fBema\&.hpp\fP"
.br
.ti -1c
.RI "file \fBexpression\&.hpp\fP"
.br
.ti -1c
.RI "file \fBientropy\&.hpp\fP"
.br
.ti -1c
.RI "file \fBmath\&.hpp\fP"
.br
.ti -1c
.RI "file \fBnormalize\&.hpp\fP"
.br
.ti -1c
.RI "file \fBorientation\&.hpp\fP"
.br
.ti -1c
.RI "file \fBpowerlaw_distribution\&.hpp\fP"
.br
.ti -1c
.RI "file \fBradians\&.hpp\fP"
.br
.ti -1c
.RI "file \fBrange\&.hpp\fP"
.br
.ti -1c
.RI "file \fBrng\&.hpp\fP"
.br
.ti -1c
.RI "file \fBrngm\&.hpp\fP"
.br
.ti -1c
.RI "file \fBsigmoid\&.hpp\fP"
.br
.ti -1c
.RI "file \fBspatial\&.hpp\fP"
.br
.ti -1c
.RI "file \fBsphere_vector\&.hpp\fP"
.br
.ti -1c
.RI "file \fBvector2\&.hpp\fP"
.br
.ti -1c
.RI "file \fBvector3\&.hpp\fP"
.br
.in -1c
