.TH "/home/jharwell/git/rcppsw/include/rcppsw/control/aperiodic_waveform.hpp" 3 "Sat Feb 5 2022" "RCPPSW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/jharwell/git/rcppsw/include/rcppsw/control/aperiodic_waveform.hpp
.SH SYNOPSIS
.br
.PP
\fC#include 'rcppsw/control/base_waveform\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBrcppsw::control::constant_waveform\fP"
.br
.RI "A special waveform that always returns a constant value: the amplitude of the waveform config it was passed during construction\&. All other parameters are ignored\&. "
.ti -1c
.RI "class \fBrcppsw::control::null_waveform\fP"
.br
.RI "A special waveform that always returns 0\&.0, indicating that there is no waveform/nothing\&. All parameters are ignored during initialization\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBrcppsw\fP"
.br
.RI "The root namespace of the RCPPSW library\&. "
.ti -1c
.RI " \fBrcppsw::control\fP"
.br
.RI "Control theory classes: periodic/aperiodic waveform generators, PID loops, etc\&. and their configuration\&. "
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBCopyright\fP
.RS 4
2018 John Harwell\&.
.RE
.PP
This file is part of RCPPSW\&.
.PP
RCPPSW is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version\&.
.PP
RCPPSW is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE\&. See the GNU General Public License for more details\&.
.PP
You should have received a copy of the GNU General Public License along with RCPPSW\&. If not, see <http://www.gnu.org/licenses/ 
.SH "Author"
.PP 
Generated automatically by Doxygen for RCPPSW from the source code\&.
