.TH "/home/jharwell/git/rcppsw/include/rcppsw/algorithm/clustering/base_clustering_impl.hpp" 3 "Sat Feb 5 2022" "RCPPSW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/jharwell/git/rcppsw/include/rcppsw/algorithm/clustering/base_clustering_impl.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <vector>\fP
.br
\fC#include <functional>\fP
.br
\fC#include 'rcppsw/rcppsw\&.hpp'\fP
.br
\fC#include 'rcppsw/algorithm/clustering/cluster\&.hpp'\fP
.br
\fC#include 'rcppsw/algorithm/clustering/membership_policy\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "interface \fBrcppsw::algorithm::clustering::base_clustering_impl< T, Policy >\fP"
.br
.RI "Templated class interface to guide the implementation of various clustering algorithms by giving them a necessary set of functions to implement so that they can be then run in an implementation agnostic way\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBrcppsw\fP"
.br
.RI "The root namespace of the RCPPSW library\&. "
.ti -1c
.RI " \fBrcppsw::algorithm\fP"
.br
.RI "Various algorithms: closest pair, max subarray, clustering\&. "
.ti -1c
.RI " \fBrcppsw::algorithm::clustering\fP"
.br
.RI "Different clustering algorithms: kmeans, entropy\&. "
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBCopyright\fP
.RS 4
2018 John Harwell, All rights reserved\&.
.RE
.PP
This file is part of RCPPSW\&.
.PP
RCPPSW is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version\&.
.PP
RCPPSW is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE\&. See the GNU General Public License for more details\&.
.PP
You should have received a copy of the GNU General Public License along with RCPPSW\&. If not, see <http://www.gnu.org/licenses/ 
.SH "Author"
.PP 
Generated automatically by Doxygen for RCPPSW from the source code\&.
