.TH "/home/jharwell/git/rcppsw/include/rcppsw/math/ema.hpp" 3 "Sat Feb 5 2022" "RCPPSW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/jharwell/git/rcppsw/include/rcppsw/math/ema.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <cmath>\fP
.br
\fC#include 'rcppsw/math/expression\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBrcppsw::math::ema< T >\fP"
.br
.RI "Calculates an Exponential Moving Average of SOMETHING\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBrcppsw\fP"
.br
.RI "The root namespace of the RCPPSW library\&. "
.ti -1c
.RI " \fBrcppsw::math\fP"
.br
.RI "Pure mathematical classes such as vectors, ranges, sigmoids, etc\&. "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<class T , class U > ema< T > \fBrcppsw::math::operator*\fP (const ema< T > &lhs, const U &rhs)"
.br
.ti -1c
.RI "template<class T , class U > ema< T > \fBrcppsw::math::operator*\fP (const U &lhs, const ema< T > &rhs)"
.br
.ti -1c
.RI "template<class T , class U > ema< T > \fBrcppsw::math::operator\-\fP (const ema< T > &lhs, const U &rhs)"
.br
.ti -1c
.RI "template<class T , class U > ema< T > \fBrcppsw::math::operator\-\fP (const U &lhs, const ema< T > &rhs)"
.br
.ti -1c
.RI "template<class T > ema< T > \fBrcppsw::math::operator/\fP (const ema< T > &lhs, const double &rhs)"
.br
.ti -1c
.RI "template<class T , class U > ema< T > \fBrcppsw::math::operator/\fP (const U &lhs, const ema< T > &rhs)"
.br
.ti -1c
.RI "template<typename T , typename std::enable_if<(!(std::is_floating_point< T >::value)), int >::type  = 0> bool \fBrcppsw::math::operator==\fP (const T &v, const ema< T > &rhs)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBCopyright\fP
.RS 4
2018 John Harwell, All rights reserved\&.
.RE
.PP
This file is part of RCPPSW\&.
.PP
RCPPSW is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version\&.
.PP
RCPPSW is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE\&. See the GNU General Public License for more details\&.
.PP
You should have received a copy of the GNU General Public License along with RCPPSW\&. If not, see <http://www.gnu.org/licenses/ 
.SH "Author"
.PP 
Generated automatically by Doxygen for RCPPSW from the source code\&.
