.TH "/home/jharwell/git/rcppsw/include/rcppsw/er/er.hpp" 3 "Sat Feb 5 2022" "RCPPSW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/jharwell/git/rcppsw/include/rcppsw/er/er.hpp
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#\fBdefine\fP \fBLIBRA_ER_ALL\fP   2 /* All event reporting  */"
.br
.ti -1c
.RI "#\fBdefine\fP \fBLIBRA_ER_FATAL\fP   1 /* Fatal events only */"
.br
.ti -1c
.RI "#\fBdefine\fP \fBLIBRA_ER_NONE\fP   0 /* No event reporting */"
.br
.ti -1c
.RI "#\fBdefine\fP \fBRCPPSW_ER\fP   LIBRA_ER"
.br
.ti -1c
.RI "#\fBdefine\fP \fBRCPPSW_ER_ALL\fP   \fBLIBRA_ER_ALL\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBRCPPSW_ER_FATAL\fP   \fBLIBRA_ER_FATAL\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBRCPPSW_ER_FATAL_MSG_LEN_MAX\fP   10000"
.br
.ti -1c
.RI "#\fBdefine\fP \fBRCPPSW_ER_MSG_LEN_MAX\fP   1000"
.br
.ti -1c
.RI "#\fBdefine\fP \fBRCPPSW_ER_NONE\fP   \fBLIBRA_ER_NONE\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBCopyright\fP
.RS 4
2021 John Harwell, All rights reserved\&.
.RE
.PP
This file is part of RCPPSW\&.
.PP
RCPPSW is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version\&.
.PP
RCPPSW is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE\&. See the GNU General Public License for more details\&.
.PP
You should have received a copy of the GNU General Public License along with RCPPSW\&. If not, see <http://www.gnu.org/licenses/ 
.SH "Macro Definition Documentation"
.PP 
.SS "#\fBdefine\fP LIBRA_ER_ALL   2 /* All event reporting  */"

.SS "#\fBdefine\fP LIBRA_ER_FATAL   1 /* Fatal events only */"

.SS "#\fBdefine\fP LIBRA_ER_NONE   0 /* No event reporting */"

.SS "#\fBdefine\fP RCPPSW_ER   LIBRA_ER"

.SS "#\fBdefine\fP RCPPSW_ER_ALL   \fBLIBRA_ER_ALL\fP"

.SS "#\fBdefine\fP RCPPSW_ER_FATAL   \fBLIBRA_ER_FATAL\fP"

.SS "#\fBdefine\fP RCPPSW_ER_FATAL_MSG_LEN_MAX   10000"

.SS "#\fBdefine\fP RCPPSW_ER_MSG_LEN_MAX   1000"

.SS "#\fBdefine\fP RCPPSW_ER_NONE   \fBLIBRA_ER_NONE\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for RCPPSW from the source code\&.
