.TH "/home/jharwell/git/rcppsw/include/rcppsw/ds/metrics/grid2D_metrics_data.hpp" 3 "Sat Feb 5 2022" "RCPPSW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/jharwell/git/rcppsw/include/rcppsw/ds/metrics/grid2D_metrics_data.hpp
.SH SYNOPSIS
.br
.PP
\fC#include 'rcppsw/metrics/base_data\&.hpp'\fP
.br
\fC#include 'rcppsw/ds/grid2D\&.hpp'\fP
.br
\fC#include 'rcppsw/al/multithread\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "interface \fBrcppsw::ds::metrics::grid2D_metrics_data\fP"
.br
.RI "Container for basic metrics gather from \fBrds::grid2D\fP\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBrcppsw\fP"
.br
.RI "The root namespace of the RCPPSW library\&. "
.ti -1c
.RI " \fBrcppsw::ds\fP"
.br
.RI "Data structures: 2D/3D lattice grids, 2D/3D discretizing grids to overlay onto continuous space, Poisson queue, rtree for 2D space, heterogeneous stacked 2D grid, type map for using in C++ quasi-reflection\&. "
.ti -1c
.RI " \fBrcppsw::ds::metrics\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for RCPPSW from the source code\&.
