.TH "/home/jharwell/git/rcppsw/include/rcppsw/algorithm/clustering/membership_policy.hpp" 3 "Sat Feb 5 2022" "RCPPSW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/jharwell/git/rcppsw/include/rcppsw/algorithm/clustering/membership_policy.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <vector>\fP
.br
\fC#include <unordered_set>\fP
.br
\fC#include 'rcppsw/rcppsw\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBrcppsw::algorithm::clustering::membership::mapping< Policy, Enable >\fP"
.br
.ti -1c
.RI "struct \fBrcppsw::algorithm::clustering::membership::mapping< Policy, policy::is_eh< Policy > >\fP"
.br
.ti -1c
.RI "struct \fBrcppsw::algorithm::clustering::membership::mapping< Policy, policy::is_nc< Policy > >\fP"
.br
.ti -1c
.RI "class \fBrcppsw::algorithm::clustering::policy::EH\fP"
.br
.RI "\fBEH\fP -> Event Horizon\&. "
.ti -1c
.RI "class \fBrcppsw::algorithm::clustering::policy::NC\fP"
.br
.RI "\fBNC\fP -> Nearest centroid\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBrcppsw\fP"
.br
.RI "The root namespace of the RCPPSW library\&. "
.ti -1c
.RI " \fBrcppsw::algorithm\fP"
.br
.RI "Various algorithms: closest pair, max subarray, clustering\&. "
.ti -1c
.RI " \fBrcppsw::algorithm::clustering\fP"
.br
.RI "Different clustering algorithms: kmeans, entropy\&. "
.ti -1c
.RI " \fBrcppsw::algorithm::clustering::membership\fP"
.br
.ti -1c
.RI " \fBrcppsw::algorithm::clustering::policy\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "template<typename Policy > using \fBrcppsw::algorithm::clustering::policy::is_eh\fP = typename std::enable_if_t< is_eh_< Policy >::value >"
.br
.ti -1c
.RI "template<typename Policy > using \fBrcppsw::algorithm::clustering::policy::is_eh_\fP = std::is_same< Policy, EH >"
.br
.ti -1c
.RI "template<typename Policy > using \fBrcppsw::algorithm::clustering::policy::is_nc\fP = typename std::enable_if_t< is_nc_< Policy >::value >"
.br
.ti -1c
.RI "template<typename Policy > using \fBrcppsw::algorithm::clustering::policy::is_nc_\fP = std::is_same< Policy, NC >"
.br
.ti -1c
.RI "template<typename Policy > using \fBrcppsw::algorithm::clustering::membership_type\fP = typename membership::mapping< Policy >::type"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBCopyright\fP
.RS 4
2018 John Harwell, All rights reserved\&.
.RE
.PP
This file is part of RCPPSW\&.
.PP
RCPPSW is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version\&.
.PP
RCPPSW is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE\&. See the GNU General Public License for more details\&.
.PP
You should have received a copy of the GNU General Public License along with RCPPSW\&. If not, see <http://www.gnu.org/licenses/ 
.SH "Class Documentation"
.PP 
.SH "struct rcppsw::algorithm::clustering::membership::mapping"
.PP 

.SS "template<typename Policy, typename Enable = void>
.br
struct rcppsw::algorithm::clustering::membership::mapping< Policy, Enable >"

.SH "struct rcppsw::algorithm::clustering::membership::mapping< Policy, policy::is_eh< Policy > >"
.PP 

.SS "template<typename Policy>
.br
struct rcppsw::algorithm::clustering::membership::mapping< Policy, policy::is_eh< Policy > >"

.PP
\fBClass Members:\fP
.RS 4
typedef vector< unordered_set< size_t > > \fItype\fP 
.br
.PP
.RE
.PP
.SH "struct rcppsw::algorithm::clustering::membership::mapping< Policy, policy::is_nc< Policy > >"
.PP 

.SS "template<typename Policy>
.br
struct rcppsw::algorithm::clustering::membership::mapping< Policy, policy::is_nc< Policy > >"

.PP
\fBClass Members:\fP
.RS 4
typedef vector< size_t > \fItype\fP 
.br
.PP
.RE
.PP
.SH "class rcppsw::algorithm::clustering::policy::EH"
.PP 
\fBEH\fP -> Event Horizon\&. 
.SH "class rcppsw::algorithm::clustering::policy::NC"
.PP 
\fBNC\fP -> Nearest centroid\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for RCPPSW from the source code\&.
