.TH "/home/jharwell/git/rcppsw/include/rcppsw/al/multithread.hpp" 3 "Sat Feb 5 2022" "RCPPSW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/jharwell/git/rcppsw/include/rcppsw/al/multithread.hpp
.SH SYNOPSIS
.br
.PP
\fC#include 'rcppsw/rcppsw\&.hpp'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBrcppsw\fP"
.br
.RI "The root namespace of the RCPPSW library\&. "
.ti -1c
.RI " \fBrcppsw::al\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "using \fBrcppsw::al::mt_double_t\fP = double"
.br
.ti -1c
.RI "using \fBrcppsw::al::mt_size_t\fP = std::size_t"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename U , typename V > void \fBrcppsw::al::mt_add\fP (U &lhs, const V &rhs)"
.br
.ti -1c
.RI "template<typename LHS , typename RHS > void \fBrcppsw::al::mt_init\fP (LHS *lhs, RHS rhs)"
.br
.ti -1c
.RI "template<typename T > T \fBrcppsw::al::mt_load\fP (const T &value)"
.br
.ti -1c
.RI "template<typename U , typename V > void \fBrcppsw::al::mt_set\fP (U &lhs, const V &rhs)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBCopyright\fP
.RS 4
2021 John Harwell, All rights reserved\&.
.RE
.PP
This file is part of RCPPSW\&.
.PP
RCPPSW is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version\&.
.PP
RCPPSW is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE\&. See the GNU General Public License for more details\&.
.PP
You should have received a copy of the GNU General Public License along with RCPPSW\&. If not, see <http://www.gnu.org/licenses/ 
.SH "Author"
.PP 
Generated automatically by Doxygen for RCPPSW from the source code\&.
