.TH "/home/jharwell/git/rcppsw/include/rcppsw/ds/poisson_queue.hpp" 3 "Sat Feb 5 2022" "RCPPSW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/jharwell/git/rcppsw/include/rcppsw/ds/poisson_queue.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <boost/optional\&.hpp>\fP
.br
\fC#include <deque>\fP
.br
\fC#include 'rcsw/common/fpc\&.h'\fP
.br
\fC#include 'rcppsw/math/rng\&.hpp'\fP
.br
\fC#include 'rcppsw/rcppsw\&.hpp'\fP
.br
\fC#include 'rcppsw/types/timestep\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBrcppsw::ds::poisson_queue< T >\fP"
.br
.RI "A wrapper around std::queue to make it more amenable to queueing theoretic analysis by tracking queue state\&. "
.ti -1c
.RI "struct \fBrcppsw::ds::poisson_queue< T >::op_metadata\fP"
.br
.RI "Metadata for tracking enqueue_queue/dequeue operations\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBrcppsw\fP"
.br
.RI "The root namespace of the RCPPSW library\&. "
.ti -1c
.RI " \fBrcppsw::ds\fP"
.br
.RI "Data structures: 2D/3D lattice grids, 2D/3D discretizing grids to overlay onto continuous space, Poisson queue, rtree for 2D space, heterogeneous stacked 2D grid, type map for using in C++ quasi-reflection\&. "
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBCopyright\fP
.RS 4
2020 John Harwell, All rights reserved\&.
.RE
.PP
This file is part of RCPPSW\&.
.PP
RCPPSW is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version\&.
.PP
RCPPSW is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE\&. See the GNU General Public License for more details\&.
.PP
You should have received a copy of the GNU General Public License along with RCPPSW\&. If not, see <http://www.gnu.org/licenses/ 
.SH "Class Documentation"
.PP 
.SH "struct rcppsw::ds::poisson_queue::op_metadata"
.PP 

.SS "template<typename T>
.br
struct rcppsw::ds::poisson_queue< T >::op_metadata"
Metadata for tracking enqueue_queue/dequeue operations\&. 
.PP
\fBClass Members:\fP
.RS 4
size_t \fIcount\fP The # of operations since the last reset\&. 
.br
.PP
timestep \fIinterval_accum\fP The accumulated time between operations since the last reset\&. 
.br
.PP
size_t \fItotal_count\fP The # of operations since the beginning of time\&. 
.br
.PP
timestep \fItotal_interval_accum\fP The accumulated time between operations since the beginning of time\&. 
.br
.PP
.RE
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for RCPPSW from the source code\&.
