.TH "polymorphic_accept_set< T, Ts... >" 3 "Sat Feb 5 2022" "RCPPSW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
polymorphic_accept_set< T, Ts... >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <polymorphic_visitable\&.hpp>\fP
.PP
Inherits polymorphic_accept_set_helper< T >, and \fBpolymorphic_accept_set< Ts\&.\&.\&. >\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for RCPPSW from the source code\&.
