.TH "rcppsw::math::euler_angles" 3 "Sat Feb 5 2022" "RCPPSW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rcppsw::math::euler_angles \- A class representing the orientation of a point or body in space using Euler angles\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <orientation\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBeuler_angles\fP (const \fBrmath::radians\fP &\fBx\fP, const \fBrmath::radians\fP &\fBy\fP, const \fBrmath::radians\fP &\fBz\fP)"
.br
.ti -1c
.RI "\fBeuler_angles\fP (void)=default"
.br
.RI "Initializes to (0,0,0)\&. "
.ti -1c
.RI "const \fBrmath::radians\fP & \fBx\fP (void) const"
.br
.ti -1c
.RI "const \fBrmath::radians\fP & \fBy\fP (void) const"
.br
.ti -1c
.RI "const \fBrmath::radians\fP & \fBz\fP (void) const"
.br
.in -1c
.SH "Detailed Description"
.PP 
A class representing the orientation of a point or body in space using Euler angles\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "rcppsw::math::euler_angles::euler_angles (void)\fC [default]\fP"

.PP
Initializes to (0,0,0)\&. 
.SS "rcppsw::math::euler_angles::euler_angles (const \fBrmath::radians\fP & x, const \fBrmath::radians\fP & y, const \fBrmath::radians\fP & z)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "const \fBrmath::radians\fP& rcppsw::math::euler_angles::x (void) const\fC [inline]\fP"

.SS "const \fBrmath::radians\fP& rcppsw::math::euler_angles::y (void) const\fC [inline]\fP"

.SS "const \fBrmath::radians\fP& rcppsw::math::euler_angles::z (void) const\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for RCPPSW from the source code\&.
