.TH "rcppsw::patterns::singleton" 3 "Sat Feb 5 2022" "RCPPSW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rcppsw::patterns::singleton \- Interfaces for the singleton design pattern\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBsingleton\fP"
.br
.RI "Define a class as incapable of being moved, copied, etc\&., and that there can only ever be one of\&. The only restriction on derived classes is that the must have a zero parameter constructor available\&. "
.in -1c
.SH "Detailed Description"
.PP 
Interfaces for the singleton design pattern\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for RCPPSW from the source code\&.
