.TH "rcppsw::ds::graph::hgrid3D_vertex_property" 3 "Sat Feb 5 2022" "RCPPSW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rcppsw::ds::graph::hgrid3D_vertex_property \- Base class for all vertex properties used with the \fBhgrid3D\fP graph\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <hgrid3D_vertex_property\&.hpp>\fP
.PP
Inherits \fBrcppsw::ds::graph::base_vertex_property\fP\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBrmath::vector3z\fP \fBcoord\fP {}"
.br
.in -1c
.SH "Detailed Description"
.PP 
Base class for all vertex properties used with the \fBhgrid3D\fP graph\&. 
.SH "Member Data Documentation"
.PP 
.SS "\fBrmath::vector3z\fP rcppsw::ds::graph::hgrid3D_vertex_property::coord {}"


.SH "Author"
.PP 
Generated automatically by Doxygen for RCPPSW from the source code\&.
