.TH "rcppsw::patterns" 3 "Sat Feb 5 2022" "RCPPSW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rcppsw::patterns \- Design pattern templates and interfaces\&.  

.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBdecorator\fP"
.br
.RI "Decorator design pattern: pointer and member variants\&. "
.ti -1c
.RI " \fBfactory\fP"
.br
.RI "Factory design pattern: sharing/releasing, multifactory\&. "
.ti -1c
.RI " \fBfsm\fP"
.br
.RI "The Finite State Machine (FSM) design pattern: simple and hierarchical variants\&. "
.ti -1c
.RI " \fBpimpl\fP"
.br
.RI "The PIMPL design pattern (the boost candidate did not work)\&. "
.ti -1c
.RI " \fBprototype\fP"
.br
.RI "Prototype design pattern interfaces and classes: clonable, caching factory\&. "
.ti -1c
.RI " \fBsingleton\fP"
.br
.RI "Interfaces for the singleton design pattern\&. "
.ti -1c
.RI " \fBvisitor\fP"
.br
.RI "Visitor design pattern variants: polymorphic, filtered, etc\&. "
.in -1c
.SH "Detailed Description"
.PP 
Design pattern templates and interfaces\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for RCPPSW from the source code\&.
