.TH "rcppsw::algorithm::clustering::eh_clustering_impl< T >" 3 "Sat Feb 5 2022" "RCPPSW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rcppsw::algorithm::clustering::eh_clustering_impl< T > \- Templated implementation class interface to guide the implementation of various Event Horizon (EH) clustering algorithms\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <eh_clustering_impl\&.hpp>\fP
.PP
Inherits \fBrcppsw::algorithm::clustering::base_clustering_impl< T, policy::EH >\fP\&.
.PP
Inherited by \fBrcppsw::algorithm::clustering::entropy_eh_omp< T >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB~eh_clustering_impl\fP (void) override=default"
.br
.ti -1c
.RI "void \fBhorizon\fP (double horizon)"
.br
.ti -1c
.RI "double \fBhorizon\fP (void) const"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 

.SS "template<typename T>
.br
interface rcppsw::algorithm::clustering::eh_clustering_impl< T >"
Templated implementation class interface to guide the implementation of various Event Horizon (EH) clustering algorithms\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename T > \fBrcppsw::algorithm::clustering::eh_clustering_impl\fP< T >::~\fBeh_clustering_impl\fP (void)\fC [override]\fP, \fC [default]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<typename T > void \fBrcppsw::algorithm::clustering::eh_clustering_impl\fP< T >::horizon (double horizon)\fC [inline]\fP"

.SS "template<typename T > double \fBrcppsw::algorithm::clustering::eh_clustering_impl\fP< T >::horizon (void) const\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for RCPPSW from the source code\&.
