.TH "rcppsw::patterns::visitor::detail::polymorphic_accept_set_helper< T >" 3 "Sat Feb 5 2022" "RCPPSW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rcppsw::patterns::visitor::detail::polymorphic_accept_set_helper< T > \- Helper class to provide the actual implementation of the visitor pattern, receiving end\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <polymorphic_visitable\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB~polymorphic_accept_set_helper\fP (void)=default"
.br
.ti -1c
.RI "virtual void \fBaccept\fP (T &visitor)=0"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename T>
.br
class rcppsw::patterns::visitor::detail::polymorphic_accept_set_helper< T >"
Helper class to provide the actual implementation of the visitor pattern, receiving end\&. 


.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP The type to accept\&. 
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename T > virtual \fBrcppsw::patterns::visitor::detail::polymorphic_accept_set_helper\fP< T >::~\fBpolymorphic_accept_set_helper\fP (void)\fC [virtual]\fP, \fC [default]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<typename T > virtual void \fBrcppsw::patterns::visitor::detail::polymorphic_accept_set_helper\fP< T >::accept (T & visitor)\fC [pure virtual]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for RCPPSW from the source code\&.
