.TH "rcppsw::metrics::config::metrics_config" 3 "Sat Feb 5 2022" "RCPPSW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rcppsw::metrics::config::metrics_config
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <metrics_config\&.hpp>\fP
.PP
Inherits \fBrcppsw::config::base_config\fP\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "rmconfig::file_sink_config \fBcsv\fP {}"
.br
.ti -1c
.RI "fs::path \fBmetrics_path\fP {}"
.br
.RI "Path to the output directory for metrics RELATIVE to the overall output directory\&. "
.ti -1c
.RI "rmconfig::network_sink_config \fBnetwork\fP {}"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Member Data Documentation"
.PP 
.SS "rmconfig::file_sink_config rcppsw::metrics::config::metrics_config::csv {}"

.SS "fs::path rcppsw::metrics::config::metrics_config::metrics_path {}"

.PP
Path to the output directory for metrics RELATIVE to the overall output directory\&. 
.SS "rmconfig::network_sink_config rcppsw::metrics::config::metrics_config::network {}"


.SH "Author"
.PP 
Generated automatically by Doxygen for RCPPSW from the source code\&.
