.TH "rcppsw::mpl::can_static_cast< T, U, std::void_t< decltype(static_cast< U >(std::declval< T >()))> >" 3 "Sat Feb 5 2022" "RCPPSW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rcppsw::mpl::can_static_cast< T, U, std::void_t< decltype(static_cast< U >(std::declval< T >()))> >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <mpl\&.hpp>\fP
.PP
Inherits true_type\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for RCPPSW from the source code\&.
