.TH "rcppsw::mpl::is_specialization< T, Template >" 3 "Sat Feb 5 2022" "RCPPSW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rcppsw::mpl::is_specialization< T, Template > \- Determine if a class Template<SomeType> is a specialization of \fCTemplate\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <mpl\&.hpp>\fP
.PP
Inherits false_type\&.
.SH "Detailed Description"
.PP 

.SS "template<class T, template< class\&.\&.\&. > class Template>
.br
struct rcppsw::mpl::is_specialization< T, Template >"
Determine if a class Template<SomeType> is a specialization of \fCTemplate\fP\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for RCPPSW from the source code\&.
