.TH "rcppsw::control::constant_waveform" 3 "Sat Feb 5 2022" "RCPPSW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rcppsw::control::constant_waveform \- A special waveform that always returns a constant value: the amplitude of the waveform config it was passed during construction\&. All other parameters are ignored\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <aperiodic_waveform\&.hpp>\fP
.PP
Inherits \fBrcppsw::control::base_waveform\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBconstant_waveform\fP (const struct \fBconfig::waveform_config\fP *const config)"
.br
.ti -1c
.RI "double \fBvalue\fP (double) override"
.br
.RI "Get the current value of the waveform at time \fCt\fP\&. "
.in -1c
.SH "Detailed Description"
.PP 
A special waveform that always returns a constant value: the amplitude of the waveform config it was passed during construction\&. All other parameters are ignored\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "rcppsw::control::constant_waveform::constant_waveform (const struct \fBconfig::waveform_config\fP *const config)\fC [inline]\fP, \fC [explicit]\fP"

.SH "Member Function Documentation"
.PP 
.SS "double rcppsw::control::constant_waveform::value (double time)\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Get the current value of the waveform at time \fCt\fP\&. 
.PP
Implements \fBrcppsw::control::base_waveform\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for RCPPSW from the source code\&.
