.TH "rcppsw::ds::graph::detail::is_decorator< T, typename >" 3 "Sat Feb 5 2022" "RCPPSW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rcppsw::ds::graph::detail::is_decorator< T, typename > \- Determine if\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <graphml\&.hpp>\fP
.PP
Inherits false_type\&.
.SH "Detailed Description"
.PP 

.SS "template<typename T, typename = void>
.br
struct rcppsw::ds::graph::detail::is_decorator< T, typename >"
Determine if\&. 


.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP is derived from \fBrpdecorator::decorator\fP\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for RCPPSW from the source code\&.
