.TH "rcppsw::math::rngm" 3 "Sat Feb 5 2022" "RCPPSW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rcppsw::math::rngm \- Random Number Generator (RNG) Manager\&. A caching factory that returns references to previously created objects rather than creating new objects each time like a regular factory\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <rngm\&.hpp>\fP
.PP
Inherits \fBrcppsw::patterns::prototype::caching_factory< rng, uint >\fP, and \fBrcppsw::patterns::singleton::singleton< rngm >\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Random Number Generator (RNG) Manager\&. A caching factory that returns references to previously created objects rather than creating new objects each time like a regular factory\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for RCPPSW from the source code\&.
