.TH "rcppsw::patterns::fsm::state_guard_condition0< SM, Func >" 3 "Sat Feb 5 2022" "RCPPSW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rcppsw::patterns::fsm::state_guard_condition0< SM, Func >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <state_guard_action\&.hpp>\fP
.PP
Inherits \fBrcppsw::patterns::fsm::state_guard\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB~state_guard_condition0\fP (void) override=default"
.br
.ti -1c
.RI "bool \fBinvoke_guard_condition\fP (\fBbase_fsm\fP *sm, const \fBevent_data\fP *) const override"
.br
.RI "Called by the state machine engine to execute a guard condition action\&. If guard condition evaluates to TRUE the state action is executed\&. If FALSE, no state transition is performed\&. "
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class SM, bool(SM::*)(void) Func>
.br
class rcppsw::patterns::fsm::state_guard_condition0< SM, Func >"

.PP
\fBTemplate Parameters\fP
.RS 4
\fISM\fP A state machine class\&. 
.br
\fIFunc\fP A state machine member function pointer that takes ZERO arguments\&. 
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<class SM , bool(SM::*)(void) Func> \fBrcppsw::patterns::fsm::state_guard_condition0\fP< SM, Func >::~\fBstate_guard_condition0\fP (void)\fC [override]\fP, \fC [default]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<class SM , bool(SM::*)(void) Func> bool \fBrcppsw::patterns::fsm::state_guard_condition0\fP< SM, Func >::invoke_guard_condition (\fBbase_fsm\fP * sm, const \fBevent_data\fP *) const\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Called by the state machine engine to execute a guard condition action\&. If guard condition evaluates to TRUE the state action is executed\&. If FALSE, no state transition is performed\&. 
.PP
\fBParameters\fP
.RS 4
\fIsm\fP A state machine instance\&.
.RE
.PP
\fBReturns\fP
.RS 4
Returns TRUE if no guard condition or the guard condition evaluates to TRUE\&. 
.RE
.PP

.PP
Implements \fBrcppsw::patterns::fsm::state_guard\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for RCPPSW from the source code\&.
