.TH "rcppsw::mpl::can_static_cast< T, U, typename >" 3 "Sat Feb 5 2022" "RCPPSW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rcppsw::mpl::can_static_cast< T, U, typename > \- Determine if \fCT\fP can be cast to \fCU\fP via static_cast<>\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <mpl\&.hpp>\fP
.PP
Inherits false_type\&.
.SH "Detailed Description"
.PP 

.SS "template<typename T, typename U, typename = void>
.br
struct rcppsw::mpl::can_static_cast< T, U, typename >"
Determine if \fCT\fP can be cast to \fCU\fP via static_cast<>\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for RCPPSW from the source code\&.
