.TH "rcppsw::control::config::xml" 3 "Sat Feb 5 2022" "RCPPSW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rcppsw::control::config::xml
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBwaveform_parser\fP"
.br
.RI "Parses XML configuration related to temporal waveform generation into \fBwaveform_config\fP\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for RCPPSW from the source code\&.
