.TH "rcppsw::patterns::fsm::state_map_row" 3 "Sat Feb 5 2022" "RCPPSW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rcppsw::patterns::fsm::state_map_row \- A structure to hold a single row within the state map\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <state_map_row\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBstate_map_row\fP (\fBrcppsw::patterns::fsm::state\fP *\fBstate\fP)"
.br
.ti -1c
.RI "\fBrcppsw::patterns::fsm::state\fP * \fBstate\fP (void) const"
.br
.in -1c
.SH "Detailed Description"
.PP 
A structure to hold a single row within the state map\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "rcppsw::patterns::fsm::state_map_row::state_map_row (\fBrcppsw::patterns::fsm::state\fP * state)\fC [inline]\fP, \fC [explicit]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBrcppsw::patterns::fsm::state\fP* rcppsw::patterns::fsm::state_map_row::state (void) const\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for RCPPSW from the source code\&.
