.TH "rcppsw::patterns::factory::detail::factory_singleton< TBase, TType, Args >" 3 "Sat Feb 5 2022" "RCPPSW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rcppsw::patterns::factory::detail::factory_singleton< TBase, TType, Args >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <multifactory\&.hpp>\fP
.PP
Inherits \fBrcppsw::patterns::singleton::singleton< base_factory< TType, std::unique_ptr, TBase, Args\&.\&.\&. > >\fP\&.
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for RCPPSW from the source code\&.
