.TH "rcppsw::patterns::fsm::state_exit_action< SM, Func >" 3 "Sat Feb 5 2022" "RCPPSW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rcppsw::patterns::fsm::state_exit_action< SM, Func > \- \fBstate_exit_action\fP takes two template arguments:  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <state_exit_action\&.hpp>\fP
.PP
Inherits \fBrcppsw::patterns::fsm::state_exit\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB~state_exit_action\fP (void) override=default"
.br
.ti -1c
.RI "void \fBinvoke_exit_action\fP (\fBbase_fsm\fP *sm) const override"
.br
.RI "Called by the state machine engine to execute a state exit action\&. Called when leaving a state\&. "
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class SM, void(SM::*)(void) Func>
.br
class rcppsw::patterns::fsm::state_exit_action< SM, Func >"
\fBstate_exit_action\fP takes two template arguments: 


.PP
\fBTemplate Parameters\fP
.RS 4
\fISM\fP A state machine class\&. 
.br
\fIFunc\fP A state machine member function pointer\&. 
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<class SM , void(SM::*)(void) Func> \fBrcppsw::patterns::fsm::state_exit_action\fP< SM, Func >::~\fBstate_exit_action\fP (void)\fC [override]\fP, \fC [default]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<class SM , void(SM::*)(void) Func> void \fBrcppsw::patterns::fsm::state_exit_action\fP< SM, Func >::invoke_exit_action (\fBbase_fsm\fP * sm) const\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Called by the state machine engine to execute a state exit action\&. Called when leaving a state\&. 
.PP
\fBParameters\fP
.RS 4
\fIsm\fP A state machine instance\&. 
.RE
.PP

.PP
Implements \fBrcppsw::patterns::fsm::state_exit\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for RCPPSW from the source code\&.
