.TH "rcppsw::control" 3 "Sat Feb 5 2022" "RCPPSW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rcppsw::control \- Control theory classes: periodic/aperiodic waveform generators, PID loops, etc\&. and their configuration\&.  

.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBconfig\fP"
.br
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBbase_waveform\fP"
.br
.RI "Base class for all types of waveforms (in the control theory sense)\&. All waveforms have [frequency, phase, amplitude, offset] components\&. "
.ti -1c
.RI "class \fBconstant_waveform\fP"
.br
.RI "A special waveform that always returns a constant value: the amplitude of the waveform config it was passed during construction\&. All other parameters are ignored\&. "
.ti -1c
.RI "class \fBnull_waveform\fP"
.br
.RI "A special waveform that always returns 0\&.0, indicating that there is no waveform/nothing\&. All parameters are ignored during initialization\&. "
.ti -1c
.RI "class \fBpid_loop\fP"
.br
.RI "A simple PID loop class\&. "
.ti -1c
.RI "class \fBsawtooth_waveform\fP"
.br
.ti -1c
.RI "class \fBsine_waveform\fP"
.br
.ti -1c
.RI "class \fBsquare_waveform\fP"
.br
.ti -1c
.RI "class \fBwaveform_generator\fP"
.br
.RI "Factory to create waveforms of different types given the name of a waveform\&. Valid names are: "
.in -1c
.SH "Detailed Description"
.PP 
Control theory classes: periodic/aperiodic waveform generators, PID loops, etc\&. and their configuration\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for RCPPSW from the source code\&.
