.TH "rcppsw::math::config::rng_config" 3 "Sat Feb 5 2022" "RCPPSW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rcppsw::math::config::rng_config \- Parameters for \fBrng\fP objects\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <rng_config\&.hpp>\fP
.PP
Inherits \fBrcppsw::config::base_config\fP\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBseed\fP {\-1}"
.br
.RI "The seed to use\&. If -1, then the current time should be used to seed RNG\&. "
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Parameters for \fBrng\fP objects\&. 
.SH "Member Data Documentation"
.PP 
.SS "int rcppsw::math::config::rng_config::seed {\-1}"

.PP
The seed to use\&. If -1, then the current time should be used to seed RNG\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for RCPPSW from the source code\&.
