.TH "rcppsw::ds::graph::base_vertex_property" 3 "Sat Feb 5 2022" "RCPPSW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rcppsw::ds::graph::base_vertex_property \- Base class for all base_vertex properties used with all graphs\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <base_vertex_property\&.hpp>\fP
.PP
Inherited by \fBrcppsw::ds::graph::hgrid3D_vertex_property\fP\&.
.SH "Detailed Description"
.PP 
Base class for all base_vertex properties used with all graphs\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for RCPPSW from the source code\&.
