.TH "rcppsw::math::config::xml" 3 "Sat Feb 5 2022" "RCPPSW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rcppsw::math::config::xml
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBema_parser\fP"
.br
.RI "Parses XML configuration for relating to exponential moving averages (EMAs)\&. "
.ti -1c
.RI "class \fBrng_parser\fP"
.br
.RI "Parses XML configuration relating to RNG\&. "
.ti -1c
.RI "class \fBsigmoid_parser\fP"
.br
.RI "Parses XML configuration for sigmoids into \fBsigmoid_config\fP\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for RCPPSW from the source code\&.
