.TH "rcppsw::metrics::detail" 3 "Sat Feb 5 2022" "RCPPSW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rcppsw::metrics::detail
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBcreatable_collector_set_comparator\fP"
.br
.RI "Comparator for \fBset_value_type\fP objects within the \fBcreatable_collector_set\fP\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for RCPPSW from the source code\&.
