.TH "rcppsw::math::sphere_vector< T >" 3 "Sat Feb 5 2022" "RCPPSW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rcppsw::math::sphere_vector< T > \- Representation of a point in 3D space in spherical coordinates\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <sphere_vector\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBsphere_vector\fP (const T &\fBradius\fP, const \fBrmath::radians\fP &\fBzenith\fP, const \fBrmath::radians\fP &\fBazimuth\fP)"
.br
.ti -1c
.RI "const \fBrmath::radians\fP & \fBazimuth\fP (void) const"
.br
.ti -1c
.RI "const T & \fBradius\fP (void) const"
.br
.ti -1c
.RI "const \fBrmath::radians\fP & \fBzenith\fP (void) const"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class T>
.br
class rcppsw::math::sphere_vector< T >"
Representation of a point in 3D space in spherical coordinates\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<class T > \fBrcppsw::math::sphere_vector\fP< T >::\fBsphere_vector\fP (const T & radius, const \fBrmath::radians\fP & zenith, const \fBrmath::radians\fP & azimuth)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<class T > const \fBrmath::radians\fP& \fBrcppsw::math::sphere_vector\fP< T >::azimuth (void) const\fC [inline]\fP"

.SS "template<class T > const T& \fBrcppsw::math::sphere_vector\fP< T >::radius (void) const\fC [inline]\fP"

.SS "template<class T > const \fBrmath::radians\fP& \fBrcppsw::math::sphere_vector\fP< T >::zenith (void) const\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for RCPPSW from the source code\&.
