.TH "rcppsw::metrics::config::network_sink_config" 3 "Sat Feb 5 2022" "RCPPSW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rcppsw::metrics::config::network_sink_config \- Configuration for metrics which will/can be output to the network\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <network_sink_config\&.hpp>\fP
.PP
Inherits \fBrcppsw::config::base_config\fP\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "rmetrics::config::output_mode_config \fBstream\fP {}"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Configuration for metrics which will/can be output to the network\&. 
.SH "Member Data Documentation"
.PP 
.SS "rmetrics::config::output_mode_config rcppsw::metrics::config::network_sink_config::stream {}"


.SH "Author"
.PP 
Generated automatically by Doxygen for RCPPSW from the source code\&.
