.TH "rcppsw::patterns::pimpl" 3 "Sat Feb 5 2022" "RCPPSW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rcppsw::patterns::pimpl \- The PIMPL design pattern (the boost candidate did not work)\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBpimpl\fP"
.br
.RI "Super-simple templated implementation of the PIMPL idiom\&. Does not exist in boost, and the boost candidate I found had subtle memory issues when optimizations were on\&. "
.in -1c
.SH "Detailed Description"
.PP 
The PIMPL design pattern (the boost candidate did not work)\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for RCPPSW from the source code\&.
