.TH "rcppsw::patterns::fsm::state_action0< SM, Func >" 3 "Sat Feb 5 2022" "RCPPSW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rcppsw::patterns::fsm::state_action0< SM, Func >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <state_action\&.hpp>\fP
.PP
Inherits \fBrcppsw::patterns::fsm::state\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBstate_action0\fP (const \fBstate_action0\fP &)=default"
.br
.ti -1c
.RI "\fBstate_action0\fP (void)=default"
.br
.ti -1c
.RI "\fB~state_action0\fP (void) override=default"
.br
.ti -1c
.RI "int \fBinvoke_state_action\fP (\fBbase_fsm\fP *sm, \fBevent_data\fP *) const override"
.br
.RI "Called by the state machine engine to execute a state action\&. If a guard condition exists and it evaluates to false, the state action will not execute\&. "
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class SM, int(SM::*)(void) Func>
.br
class rcppsw::patterns::fsm::state_action0< SM, Func >"

.PP
\fBTemplate Parameters\fP
.RS 4
\fISM\fP A state machine class\&. 
.br
\fIFunc\fP A state machine member function pointer, which takes ZERO arguments\&. 
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<class SM , int(SM::*)(void) Func> \fBrcppsw::patterns::fsm::state_action0\fP< SM, Func >::\fBstate_action0\fP (void)\fC [default]\fP"

.SS "template<class SM , int(SM::*)(void) Func> \fBrcppsw::patterns::fsm::state_action0\fP< SM, Func >::\fBstate_action0\fP (const \fBstate_action0\fP< SM, Func > &)\fC [default]\fP"

.SS "template<class SM , int(SM::*)(void) Func> \fBrcppsw::patterns::fsm::state_action0\fP< SM, Func >::~\fBstate_action0\fP (void)\fC [override]\fP, \fC [default]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<class SM , int(SM::*)(void) Func> int \fBrcppsw::patterns::fsm::state_action0\fP< SM, Func >::invoke_state_action (\fBbase_fsm\fP * sm, \fBevent_data\fP * data) const\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Called by the state machine engine to execute a state action\&. If a guard condition exists and it evaluates to false, the state action will not execute\&. 
.PP
\fBParameters\fP
.RS 4
\fIsm\fP A state machine instance\&. 
.br
\fIdata\fP The event data\&.
.RE
.PP
\fBReturns\fP
.RS 4
integer indicating whether or not the event was handled\&. 
.RE
.PP

.PP
Implements \fBrcppsw::patterns::fsm::state\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for RCPPSW from the source code\&.
