.TH "rcppsw::al" 3 "Sat Feb 5 2022" "RCPPSW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rcppsw::al
.SH SYNOPSIS
.br
.PP
.SS "Typedefs"

.in +1c
.ti -1c
.RI "using \fBmt_double_t\fP = double"
.br
.ti -1c
.RI "using \fBmt_size_t\fP = std::size_t"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename U , typename V > void \fBmt_add\fP (U &lhs, const V &rhs)"
.br
.ti -1c
.RI "template<typename LHS , typename RHS > void \fBmt_init\fP (LHS *lhs, RHS rhs)"
.br
.ti -1c
.RI "template<typename T > T \fBmt_load\fP (const T &value)"
.br
.ti -1c
.RI "template<typename U , typename V > void \fBmt_set\fP (U &lhs, const V &rhs)"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "using \fBrcppsw::al::mt_double_t\fP = typedef double"

.SS "using \fBrcppsw::al::mt_size_t\fP = typedef std::size_t"

.SH "Function Documentation"
.PP 
.SS "template<typename U , typename V > void rcppsw::al::mt_add (U & lhs, const V & rhs)"

.SS "template<typename LHS , typename RHS > void rcppsw::al::mt_init (LHS * lhs, RHS rhs)"

.SS "template<typename T > T rcppsw::al::mt_load (const T & value)"

.SS "template<typename U , typename V > void rcppsw::al::mt_set (U & lhs, const V & rhs)"

.SH "Author"
.PP 
Generated automatically by Doxygen for RCPPSW from the source code\&.
