.TH "rcppsw::metrics::config::xml" 3 "Sat Feb 5 2022" "RCPPSW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rcppsw::metrics::config::xml
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBbase_sink_parser\fP"
.br
.RI "Base class for parsing parameters for \fBrmetrics::base_sink\fP derived classes\&. "
.ti -1c
.RI "class \fBfile_sink_parser\fP"
.br
.RI "Parses XML parameters related to the \fBrmetrics::file_sink\fP into \fBfile_sink_config\fP\&. "
.ti -1c
.RI "class \fBmetrics_parser\fP"
.br
.RI "Parses XML parameters related to metric collection into \fBmetrics_config\fP\&. "
.ti -1c
.RI "class \fBnetwork_sink_parser\fP"
.br
.RI "Parses XML parameters related to the \fBrmetrics::network_sink\fP into \fBnetwork_sink_config\fP\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for RCPPSW from the source code\&.
