.TH "rcppsw::ds::metrics::grid2D_metrics_data" 3 "Sat Feb 5 2022" "RCPPSW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rcppsw::ds::metrics::grid2D_metrics_data \- Container for basic metrics gather from \fBrds::grid2D\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <grid2D_metrics_data\&.hpp>\fP
.PP
Inherits \fBrcppsw::metrics::base_data\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBgrid2D_metrics_data\fP (const \fBmath::vector2z\fP &dims)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBrcppsw::ds::grid2D\fP< \fBral::mt_size_t\fP > \fBgrid\fP"
.br
.ti -1c
.RI "\fBral::mt_size_t\fP \fBtotal_count\fP {0}"
.br
.in -1c
.SH "Detailed Description"
.PP 
Container for basic metrics gather from \fBrds::grid2D\fP\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "rcppsw::ds::metrics::grid2D_metrics_data::grid2D_metrics_data (const \fBmath::vector2z\fP & dims)\fC [inline]\fP, \fC [explicit]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBrcppsw::ds::grid2D\fP<\fBral::mt_size_t\fP> rcppsw::ds::metrics::grid2D_metrics_data::grid"

.SS "\fBral::mt_size_t\fP rcppsw::ds::metrics::grid2D_metrics_data::total_count {0}"


.SH "Author"
.PP 
Generated automatically by Doxygen for RCPPSW from the source code\&.
