.TH "rcppsw::ds::graph::detail::is_decorator< T, std::void_t< decltype(std::declval< T >().decoratee())> >" 3 "Sat Feb 5 2022" "RCPPSW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rcppsw::ds::graph::detail::is_decorator< T, std::void_t< decltype(std::declval< T >().decoratee())> >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <graphml\&.hpp>\fP
.PP
Inherits true_type\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for RCPPSW from the source code\&.
