.TH "rcppsw::control::sawtooth_waveform" 3 "Sat Feb 5 2022" "RCPPSW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rcppsw::control::sawtooth_waveform
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <periodic_waveform\&.hpp>\fP
.PP
Inherits \fBrcppsw::control::base_waveform\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBsawtooth_waveform\fP (const struct \fBconfig::waveform_config\fP *const config)"
.br
.ti -1c
.RI "double \fBvalue\fP (double time) override"
.br
.RI "Get the current value of the waveform at time \fCt\fP\&. "
.in -1c
.SH "Detailed Description"
.PP 
Given the current time, outputs the current value of a sawtooth wave according to configured parameters:
.PP
value = amplitude * ( 2 * (t - floor(time + 0\&.5) + phase)) + offset\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "rcppsw::control::sawtooth_waveform::sawtooth_waveform (const struct \fBconfig::waveform_config\fP *const config)\fC [inline]\fP, \fC [explicit]\fP"

.SH "Member Function Documentation"
.PP 
.SS "double rcppsw::control::sawtooth_waveform::value (double time)\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Get the current value of the waveform at time \fCt\fP\&. 
.PP
Implements \fBrcppsw::control::base_waveform\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for RCPPSW from the source code\&.
