.TH "rcppsw::math::config::sigmoid_config" 3 "Sat Feb 5 2022" "RCPPSW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rcppsw::math::config::sigmoid_config \- Parameters for probabilistic exponentials (aka sigmoids)\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <sigmoid_config\&.hpp>\fP
.PP
Inherits \fBrcppsw::config::base_config\fP\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBgamma\fP {0\&.0}"
.br
.ti -1c
.RI "double \fBoffset\fP {0\&.0}"
.br
.ti -1c
.RI "double \fBreactivity\fP {0\&.0}"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Parameters for probabilistic exponentials (aka sigmoids)\&. 
.SH "Member Data Documentation"
.PP 
.SS "double rcppsw::math::config::sigmoid_config::gamma {0\&.0}"

.SS "double rcppsw::math::config::sigmoid_config::offset {0\&.0}"

.SS "double rcppsw::math::config::sigmoid_config::reactivity {0\&.0}"


.SH "Author"
.PP 
Generated automatically by Doxygen for RCPPSW from the source code\&.
