.TH "rcppsw::metrics::config" 3 "Sat Feb 5 2022" "RCPPSW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rcppsw::metrics::config
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBxml\fP"
.br
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBfile_sink_config\fP"
.br
.RI "Configuration for metrics which will/can be output as files\&. "
.ti -1c
.RI "struct \fBmetrics_config\fP"
.br
.ti -1c
.RI "struct \fBnetwork_sink_config\fP"
.br
.RI "Configuration for metrics which will/can be output to the network\&. "
.ti -1c
.RI "struct \fBoutput_mode_config\fP"
.br
.in -1c
.SH "Class Documentation"
.PP 
.SH "struct rcppsw::metrics::config::output_mode_config"
.PP 
\fBClass Members:\fP
.RS 4
typedef map< string, string > \fIenabled_map_type\fP 
.br
.PP
.RE
.PP
\fBClass Members:\fP
.RS 4
\fBenabled_map_type\fP \fIenabled\fP 
.br
.PP
timestep \fIoutput_interval\fP 
.br
.PP
.RE
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for RCPPSW from the source code\&.
