.TH "rcppsw::config::base_config" 3 "Sat Feb 5 2022" "RCPPSW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rcppsw::config::base_config \- A stub base class for any and all derived configuration class types that may need polymorphism or covariance\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <base_config\&.hpp>\fP
.PP
Inherited by \fBrcppsw::control::config::waveform_config\fP, \fBrcppsw::math::config::ema_config\fP, \fBrcppsw::math::config::rng_config\fP, \fBrcppsw::math::config::sigmoid_config\fP, \fBrcppsw::metrics::config::file_sink_config\fP, \fBrcppsw::metrics::config::metrics_config\fP, and \fBrcppsw::metrics::config::network_sink_config\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBbase_config\fP (const \fBbase_config\fP &)=default"
.br
.ti -1c
.RI "\fBbase_config\fP (void)=default"
.br
.ti -1c
.RI "virtual \fB~base_config\fP (void)=default"
.br
.ti -1c
.RI "\fBbase_config\fP & \fBoperator=\fP (const \fBbase_config\fP &)=default"
.br
.in -1c
.SH "Detailed Description"
.PP 
A stub base class for any and all derived configuration class types that may need polymorphism or covariance\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "rcppsw::config::base_config::base_config (void)\fC [default]\fP"

.SS "virtual rcppsw::config::base_config::~base_config (void)\fC [virtual]\fP, \fC [default]\fP"

.SS "rcppsw::config::base_config::base_config (const \fBbase_config\fP &)\fC [default]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBbase_config\fP& rcppsw::config::base_config::operator= (const \fBbase_config\fP &)\fC [default]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for RCPPSW from the source code\&.
