.TH "rcppsw::metrics::base_data" 3 "Sat Feb 5 2022" "RCPPSW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rcppsw::metrics::base_data \- Base class for the containers of data extracted through classes derived from \fBbase_metrics\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <base_data\&.hpp>\fP
.PP
Inherited by \fBrcppsw::ds::metrics::grid2D_metrics_data\fP, and \fBrcppsw::ds::metrics::grid3D_metrics_data\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBbase_data\fP (void)=default"
.br
.ti -1c
.RI "virtual \fB~base_data\fP (void)=default"
.br
.in -1c
.SH "Detailed Description"
.PP 
Base class for the containers of data extracted through classes derived from \fBbase_metrics\fP\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "rcppsw::metrics::base_data::base_data (void)\fC [default]\fP"

.SS "virtual rcppsw::metrics::base_data::~base_data (void)\fC [virtual]\fP, \fC [default]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for RCPPSW from the source code\&.
