.TH "visit_set< T, Ts... >" 3 "Sat Feb 5 2022" "RCPPSW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
visit_set< T, Ts... > \- Middle recursive case for expansion\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <visitor\&.hpp>\fP
.PP
Inherits visit_set_helper< T >, and \fBvisit_set< Ts\&.\&.\&. >\fP\&.
.SH "Detailed Description"
.PP 

.SS "template<typename T, typename\&.\&.\&. Ts>
.br
class visit_set< T, Ts\&.\&.\&. >"
Middle recursive case for expansion\&. 


.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP A type to visit\&. 
.br
\fITs\fP The rest of the to-be-processed types to visit\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for RCPPSW from the source code\&.
