.TH "visit_set< T >" 3 "Sat Feb 5 2022" "RCPPSW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
visit_set< T > \- Base case for expansion\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <visitor\&.hpp>\fP
.PP
Inherits visit_set_helper< T >\&.
.SH "Detailed Description"
.PP 

.SS "template<typename T>
.br
class visit_set< T >"
Base case for expansion\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for RCPPSW from the source code\&.
