name: Build and test

on:
  push:
    branches:
      - master
      - devel

jobs:
  build-and-test:
    runs-on:
      - ubuntu-22.04

    strategy:
      matrix:
        build_type:
          - OPT
          - DEV

        al_mt_safe:
          - YES
          - NO

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/rcppsw-setup

      - name: Build=${{ matrix.build_type }}, AL_MT_SAFE=${{ matrix.al_mt_safe}}
        shell: bash
        run: |

          mkdir -p build && cd build

          cmake  \
          -DCMAKE_INSTALL_PREFIX=$HOME/.local \
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
          -DRCPPSW_AL_MT_SAFE_TYPES=${{ matrix.al_mt_safe }} \
          -DLIBRA_TESTS=yes \
          -DLIBRA_CODE_COV=YES \
          -DLIBRA_ER=ALL \
          ..

          make build-and-test
          make coverage-report

          # coveralls --root .. -E '.*/ext/.*' -E '.*/CMakeFiles/.*'


      - name: Coverralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: build/coverage.info
